### ISSUE TITLE
这Bot还会更新吗，还有osu-vs-player的ReadME

### ISSUE THREAD

**Issue by IchinoseSuzune** [wasupandceacar/osubot#1]
这Bot还会更新吗，还有osu-vs-player的ReadME，根据原项目的ReadME无法正常使用osu-vs-player，能否详写一下OSU-vs-player的使用方法。

**Comment by wasupandceacar** [comment]
这个已经鸽了，白菜已经够用了。回放对比的话晚点我写一下8（也许也会鸽
